export const APP_SET_LOADING = "APP_SET_LOADING";

export const SET_PRODUCT_LOADER = "SET_PRODUCT_LOADER";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_PAGINATION_PRODUCT = "SET_PAGINATION_PRODUCT";
